### ISSUE TITLE
Logger fails when raw ASCII-8BIT string is passed

### ISSUE THREAD

**Issue by edvakf** [voyagegroup/kusabana#81]
I encountered this error every time I use.

```
$ bundle exec rake start
bundle exec bin/kusabana
message:RuntimeError    @timestamp:2014-07-08T05:06:53+09:00
message:no acceptor (port is in use or requires root privileges)    @timestamp:2014-07-08T05:06:53+09:00
message:/home/edvakf/kusabana/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server'    @timestamp:2014-07-08T05:06:53+09:00
message:/home/edvakf/kusabana/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_server'    @timestamp:2014-07-08T05:06:53+09:00
message:/home/edvakf/kusabana/lib/kusabana/proxy.rb:32:in `block in start'  @timestamp:2014-07-08T05:06:53+09:00
message:/home/edvakf/kusabana/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'    @timestamp:2014-07-08T05:06:53+09:00
message:/home/edvakf/kusabana/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine' @timestamp:2014-07-08T05:06:53+09:00
message:/home/edvakf/kusabana/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run' @timestamp:2014-07-08T05:06:53+09:00
message:/home/edvakf/kusabana/lib/kusabana/proxy.rb:28:in `start'   @timestamp:2014-07-08T05:06:53+09:00
message:bin/kusabana:29:in `<main>' @timestamp:2014-07-08T05:06:53+09:00
```

Changing `raws.join("\t")` to `raws.map{|r| r.force_encoding("UTF-8")}.join("\t")` solves, but I don't know if that's the right way to deal with it.

https://github.com/voyagegroup/kusabana/blob/master/lib/kusabana/logger.rb#L138

I'm running kusabana with ruby 2.1.0 on debian 7.0 with my server locale like this;

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by rail44** [comment]
> message:no acceptor (port is in use or requires root privileges)

port is already used, isn't it?

**Comment by edvakf** [comment]
Oops, I must have pasted a wrong log. I can't remember how I reached the logger part any more. Plus I can't reproduce it any more. I'm going to close this issue.

**Comment by rail44** [comment]
I'm sorry too late reply.
I've found that there is issue with

> incompatible character encodings: ASCII-8BIT and UTF-8

It may be fixed some days after...
